Add grandchildren method that should allow Islands to get all of their Districts via Has Many Through relationship. Does not work.
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'categories''

Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'categories' (SQL: select `categories`.*, `categories`.`parent_id` from `categories` inner join `categories` on `categories`.`id` = `categories`.`parent_id` where `section` = district and `categories`.`parent_id` = 147)

Fails due to the query building not using unique aliases for the table names. This hierarchy structure uses 1 table (categories) for everything.

It's possible this is fixed in a later version of Laravel's database component.